#ifndef IRQ_H
#define IRQ_H

#define IRQ_BASIC_PENDING	(__IO unsigned int *)(PHERIPHERAL_BASE_ADDR + 0x0000B200)
#define IRQ_PENDING_1		(__IO unsigned int *)(PHERIPHERAL_BASE_ADDR + 0x0000B204)
#define IRQ_PENDING_2		(__IO unsigned int *)(PHERIPHERAL_BASE_ADDR + 0x0000B208)
#define FIQ_CONTROL		    (__IO unsigned int *)(PHERIPHERAL_BASE_ADDR + 0x0000B20C)
#define ENABLE_IRQS_1		(__IO unsigned int *)(PHERIPHERAL_BASE_ADDR + 0x0000B210)
#define ENABLE_IRQS_2		(__IO unsigned int *)(PHERIPHERAL_BASE_ADDR + 0x0000B214)
#define ENABLE_BASIC_IRQS	(__IO unsigned int *)(PHERIPHERAL_BASE_ADDR + 0x0000B218)
#define DISABLE_IRQS_1		(__IO unsigned int *)(PHERIPHERAL_BASE_ADDR + 0x0000B21C)
#define DISABLE_IRQS_2		(__IO unsigned int *)(PHERIPHERAL_BASE_ADDR + 0x0000B220)
#define DISABLE_BASIC_IRQS	(__IO unsigned int *)(PHERIPHERAL_BASE_ADDR + 0x0000B224)



#endif